### ISSUE TITLE
[FEATURE REQUEST] Route to company only if quota is not met

### ISSUE THREAD

**Issue by yanang007** [LaChips/AutoCompanyBuilding#4]
Hi, thanks for your awesome mod! It really helps a lot!

However, there are cases that rerouting may not be necessary.
For example with [QuotaRollover](https://thunderstore.io/c/lethal-company/p/boxofbiscuits97/QuotaRollover/), a party can reach quota without landing on company. 
Or parties with [extra days](https://thunderstore.io/c/lethal-company/p/Anubis/ExtraDaysToDeadline/) may have sold scraps earlier in this round and met the quota.

It seems that adding another condition here to reroute only if quota is not met should be enough.
https://github.com/LaChips/AutoCompanyBuilding/blob/ec8e4e910f35cf01eb0306e96636bd16ed1c87c8/AutoCompanyBuilding/Patches/StartOfRoundPatch.cs#L32-L41

**Comment by LaChips** [comment]
Hey, thanks a lot for your feedback!

I checked the mods and here is what I’m thinking:

- Rerouting only if quota is not met would basically nullish the entire mod’s point in a lot of cases.

- QuotaRollover: I believe a majority of player wait for the last day to go to the Company Building, rerouting them just because they met the quota would probably be really annoying for them (plus, there is a penalty for returning early); at least more than having to reroute manually. Or am I missing the point? (The mod only allows to keep the margin after quota reset; Not sure how this conflicts with my mod tbh).

- Extra Days: my first thought was « I can’t predict wether or not the player will chose the buy a new day » and then I realized it’s kind of a non issue because, correct me if I’m wrong: 

  - The auto rerouting would end way before the player finishes buying his day -> party would not be slowed down.
  - The player will most likely reroute to another moon no matter what (in case of eclipse, storm or whatever).

I do have some sort of a solution which would be to allow players, through the terminal (better) or config files, to auto reroute when the quota is met / not met.

Let me know what you think.

Tbh, I don’t really understand the problem, I’d have to try with the mods you linked. Can you describe more precisely what happens and what you’d like to happen and in which case?

**Comment by yanang007** [comment]
Hi! Thanks for your quick response and detailed analysis! It seems that I didn't properly describe the problem.

This issue is probably a little simpler, which only focuses on the last day of a round when normally `AutoCompanyBuilding` would automatically reroute to The Company. A simple version is 
```
At the last day of a round, check if the quota is met. 
If quota is not met, reroute to The Company as normal.
If quota is already met, do nothing.
```

Here is a detailed example where we may not expect a rerouting:

For example we may have gathered $1000 in the 1st round, and with `QuotaRollover`, the rest $1000 - $130 = $870 will be saved for the next round.

Then we got the quota for the 2nd round is $260, which has been finished as there are $870 credists saved from 1st round by `QuotaRollover`. For this reason we don't even necessarily need to go to Company in this round.

So we can decide to go to titan and stay in Titan for next two rounds. 

However current `AutoCompanyBuilding` will still forcibly reroute to The Company and invalidate the ticket to Titan. Then to go to Titan we need to cost another $700.

Here is a typical example with `QuotaRollover`. At this case, the party can choose not to go to company in this round and instead spend the last day on the moon.
![screenshot](https://github.com/LaChips/AutoCompanyBuilding/assets/8695716/7afd56ce-b08d-4452-9ea0-5ddb80f1f65d)

**Comment by LaChips** [comment]
Ok I get it now. Thanks for your answer. I misunderstood the first message, sorry about that.

I’ll try to deploy a fix ASAP.

**Comment by yanang007** [comment]
That would be great! Thanks!

**Comment by LaChips** [comment]
The issue has been fixed in v.1.2.0 ([commit](https://github.com/LaChips/AutoCompanyBuilding/commit/4aac40d6126170270e6786571f652443e3b3a3df)).

Thanks for pointing this out to me!

The update should appear on Thunderstore pretty soon.

**Comment by yanang007** [comment]
That works perfectly! Thanks!
